using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace TestModule.TestModuleTables
{
    public class TestModuleTableManager : TestModuleTableManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TestModuleTableManager(ITestModuleTableRepository testModuleTableRepository)
            : base(testModuleTableRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}