using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace TestModule.TestModuleTables
{
    public class TestModuleTable : TestModuleTableBase
    {
        //<suite-custom-code-autogenerated>
        protected TestModuleTable()
        {

        }

        public TestModuleTable(Guid id, string? code = null, string? name = null, string? notes = null)
            : base(id, code, name, notes)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}