using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using TestModule.Permissions;
using TestModule.TestModuleTables;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using TestModule.Shared;

namespace TestModule.TestModuleTables
{
    public class TestModuleTablesAppService : TestModuleTablesAppServiceBase, ITestModuleTablesAppService
    {
        //<suite-custom-code-autogenerated>
        public TestModuleTablesAppService(ITestModuleTableRepository testModuleTableRepository, TestModuleTableManager testModuleTableManager, IDistributedCache<TestModuleTableDownloadTokenCacheItem, string> downloadTokenCache)
            : base(testModuleTableRepository, testModuleTableManager, downloadTokenCache)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}